### PR TITLE
Display only changed items in updating monitors

### PR DESCRIPTION
**Pull request by takus**
Hi,

barkdog

I modified `Barkdog.Driver.update_monitor` for displaying output like above. I think this is useful for knowing what parts will be changed in applying. How do you think about this change?

### CODE REVIEW

**Comment by winebarrel** [comment]
Thanks! :smiley:

**Comment by takus** [comment]
Thank you for merging :+1:

**Comment by winebarrel** [comment]
v0.1.1 has been released. Please try it out!

**Comment by takus** [comment]
:sunglasses:

**Pull request merged**
